# Development Dockerfile for backend

FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=development
ENV BACKEND_PORT=3847

EXPOSE 3847

CMD ["npm", "run", "dev"]
